import PageLoader from "@/components/PageLoader";
import { CodeProvider } from "@/context/codeContext";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
// import Notify from "@/components/Notify";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${poppins.className} antialiased bg-primary-100 dark:bg-primary-600 text-primary-900 dark:text-primary-100`}
        >
          <CodeProvider>
            <PageLoader />
            <div className="w-full max-w-[1920px] mx-auto">
              {children}
            </div>
            {/* <Notify /> */}
          </CodeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
